baseURL = "/"
languageCode = "en-us"
title = "Jeremy Hemberger"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

# pygmentsstyle = "monokai"
# pygmentscodefences = false
# pygmentscodefencesguesssyntax = true
# pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"
googleAnalytics = "UA-159229765-1"

[params]
    author = "Jeremy Hemberger"
    info = "Ecology, entomology, & science communication"
    description = "Jeremy's Personal Website"
    keywords = "blog,ecology,entomology,R,landscape"
    avatarurl = "images/jeremy_avatar.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    colorscheme = "light"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/jhemberger/"
[[params.social]]
    name = "Mastodon"
    icon = "fab fa-mastodon fa-2x"
    weight = 1
    url = "https://ecoevo.social/@hemberger#"
[[params.social]]
    name = "CV"
    icon = "fa fa-id-card"
    url = "https://www.dropbox.com/s/zuno3zdtn9o58m1/hemberger_cv_11_2022.pdf?dl=0"
    weight = 4
[[params.social]]
    name = "OrcID"
    icon = "fab fa-orcid"
    url = "https://orcid.org/0000-0003-3648-4724"
    weight = 3
[[params.social]]
    name = "Buy me a coffee"
    icon = "fa fa-coffee"
    url = "/buy-jeremy-a-coffee/"
    weight = 5

# Menu links
[menu]
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Research"
    weight = 2
    url  = "/research/"
[[menu.main]]
    name = "Teaching"
    weight = 3
    url  = "/teaching/"
[[menu.main]]
    identifier = "graphic_art"
    name = "Graphic Art"
    url = "/graphic_art/"
    weight = 7
[[menu.main]]
    identifier = "photography"
    name = "Photos"
    url = "/photography/"
    weight = 6
[[menu.main]]
    name = "Publications"
    weight = 4
    url  = "/publications/"
[[menu.main]]
    name = "#SciComm"
    weight = 5
    url  = "/scicomm/"